version: "3.9"

services:
  api:
    build: .
    container_name: dikshant_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

  mysql:
    image: mysql:8.0
    container_name: dikshant_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dikshant_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    container_name: dikshant_redis
    restart: always
    ports:
      - "6380:6379"

volumes:
  mysql_data:
